### ISSUE TITLE
Suggestion: Make tags an object of JSON schemas

### ISSUE THREAD

**Issue by willyg302** [sanathkr/lambda-sample-events#11]
Currently `tags` is an array of custom objects. Take for example Kinesis:

```json
[
  {
    "name": "region"
  },
  {
    "name": "sequence",
    "usage": "The Kinesis sequence number",
    "default": "49545115243490985018280067714973144582180062593244200961"
  },
  {
    "name": "data",
    "usage": "he Kinesis message payload. There is no need to base64 this - sam will do this for you",
    "default": "Hello, this is a test 123."
  }
]
```

We could instead encode it like this:

```json
{
  "region": {
    "$ref": "#/definitions/region"
  },
  "sequence": {
    "type": "string",
    "description": "The Kinesis sequence number",
    "default": "49545115243490985018280067714973144582180062593244200961"
  },
  "data": {
    "type": "string",
    "description": "he Kinesis message payload. There is no need to base64 this - sam will do this for you",
    "default": "Hello, this is a test 123."
  }
}
```

This has a number of benefits:

- A standard format that also provides a means of adding validation to any tag in the future
- It's possible to generate a UI for providing tag values based off a JSON schema, which building on the previous will have validation built-in
- The object you will be providing to Mustache to fill out the template is the same you pass to JSON schema to validate
- Merging with tags-mapping.json is also very easy -- note the use of a ref above, allowing you to construct a schema in JS like the following:

```js
const kinesisEventMapping = require('event-mapping.json').events.kinesis[0];
const schema = {
  type: 'object',
  properties: kinesisEventMapping.tags,
  definitions: require('tags-mapping.json'),
};
```

**Comment by sanathkr** [comment]
This is pretty cool. Let’s do this! I am very interested in ability to generate UI for these inputs.
