### ISSUE TITLE
Verify the correctness of event files - sns

### ISSUE THREAD

**Issue by willyg302** [sanathkr/lambda-sample-events#4]
#2

**Comment by willyg302** [comment]
Verified https://github.com/sanathkr/lambda-sample-events/blob/master/events/sns/Sns.json. Steps:

1. Added SNS trigger in Lambda console
2. In SNS console, clicked "Publish to topic"
3. Tried a number of different messages:
  - Raw vs JSON message
  - Various message attributes

The sample event only includes examples of a string and binary message attribute, but SNS also supports string array and number. It occurred to me that if we had JSON schemas for each event, they could be specified there (but it would be fine if the sample had just one or two for example).

**Comment by sanathkr** [comment]
Interesting. Yeah we to build JSON Schemas for each of the events. We will do that once we have verified each of these events :)
